micronaut:
  application:
    name: keyManager

grpc:
  server:
    keep-alive-time: 1h
    max-inbound-message-size: 1024

datasources:
  default:
    url: ${DB_URI:`jdbc:postgresql://localhost:5432/micronaut`}
    username: ${DB_USER:dbuser}
    password: ${DB_PASSWORD:""}
    driverClassName: ${DB_DRIVER:org.postgresql.Driver}

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: create-drop
        show_sql: true
        format_sql: true

itau:
  contas:
    url: ${ITAU_URL:`http://localhost:9091`}

bcb:
  pix:
    url: ${BCB_URL:`http://localhost:8082`}